// object detail
export const OBJECT_DETAIL_REQUEST = "OBJECT_DETAIL_REQUEST";
export const OBJECT_DETAIL_SUCCESS = "OBJECT_DETAIL_SUCCESS";
export const OBJECT_DETAIL_FAIL = "OBJECT_DETAIL_FAIL";

// object select or remove model
export const OBJECT_SELECT_OR_REMOVE_REQUEST =
  "OBJECT_SELECT_OR_REMOVE_REQUEST";
export const OBJECT_SELECT_OR_REMOVE_SUCCESS =
  "OBJECT_SELECT_OR_REMOVE_SUCCESS";
export const OBJECT_SELECT_OR_REMOVE_FAIL = "OBJECT_SELECT_OR_REMOVE_FAIL";

// object is_pinned or not model
export const OBJECT_ISPINNED_OR_NOT_REQUEST = "OBJECT_ISPINNED_OR_NOT_REQUEST";
export const OBJECT_ISPINNED_OR_NOT_SUCCESS = "OBJECT_ISPINNED_OR_NOT_SUCCESS";
export const OBJECT_ISPINNED_OR_NOT_FAIL = "OBJECT_ISPINNED_OR_NOT_FAIL";

// object set data
export const OBJECT_SET_DETAIL_DATA = "OBJECT_SET_DETAIL_DATA";
export const OBJECT_SET_MODIFY_DATA = "OBJECT_SET_MODIFY_DATA";
