// initial object detail
export const INITIAL_OBJECT_REQUEST = "INITIAL_OBJECT_REQUEST";
export const INITIAL_OBJECT_SUCCESS = "INITIAL_OBJECT_SUCCESS";
export const INITIAL_OBJECT_FAIL = "INITIAL_OBJECT_FAIL";

// initial object select or remove model
export const INITIAL_OBJECT_SELECT_OR_REMOVE_REQUEST =
  "INITIAL_OBJECT_SELECT_OR_REMOVE_REQUEST";
export const INITIAL_OBJECT_SELECT_OR_REMOVE_SUCCESS =
  "INITIAL_OBJECT_SELECT_OR_REMOVE_SUCCESS";
export const INITIAL_OBJECT_SELECT_OR_REMOVE_FAIL =
  "INITIAL_OBJECT_SELECT_OR_REMOVE_FAIL";

// initial object is_pinned or not model
export const INITIAL_OBJECT_ISPINNED_OR_NOT_REQUEST =
  "INITIAL_OBJECT_ISPINNED_OR_NOT_REQUEST";
export const INITIAL_OBJECT_ISPINNED_OR_NOT_SUCCESS =
  "INITIAL_OBJECT_ISPINNED_OR_NOT_SUCCESS";
export const INITIAL_OBJECT_ISPINNED_OR_NOT_FAIL =
  "INITIAL_OBJECT_ISPINNED_OR_NOT_FAIL";

// initial object set data
export const INITIAL_OBJECT_SET_INITIAL_DATA = "NITIAL_OBJECT_SET_INITIAL_DATA";
export const INITIAL_OBJECT_SET_SELECT_DATA = "NITIAL_OBJECT_SET_SELECT_DATA";

// ---------------------------------------------------------------
// ---------------------------------------------------------------

// object detail
export const OBJECT_DETAIL_REQUEST = "OBJECT_DETAIL_REQUEST";
export const OBJECT_DETAIL_SUCCESS = "OBJECT_DETAIL_SUCCESS";
export const OBJECT_DETAIL_FAIL = "OBJECT_DETAIL_FAIL";

// object select or remove model
export const OBJECT_SELECT_OR_REMOVE_REQUEST =
  "OBJECT_SELECT_OR_REMOVE_REQUEST";
export const OBJECT_SELECT_OR_REMOVE_SUCCESS =
  "OBJECT_SELECT_OR_REMOVE_SUCCESS";
export const OBJECT_SELECT_OR_REMOVE_FAIL = "OBJECT_SELECT_OR_REMOVE_FAIL";

// object is_pinned or not model
export const OBJECT_ISPINNED_OR_NOT_REQUEST = "OBJECT_ISPINNED_OR_NOT_REQUEST";
export const OBJECT_ISPINNED_OR_NOT_SUCCESS = "OBJECT_ISPINNED_OR_NOT_SUCCESS";
export const OBJECT_ISPINNED_OR_NOT_FAIL = "OBJECT_ISPINNED_OR_NOT_FAIL";

// object set data
export const OBJECT_SET_INITIAL_DATA = "OBJECT_SET_INITIAL_DATA";
export const OBJECT_SET_SELECT_DATA = "OBJECT_SET_SELECT_DATA";
export const OBJECT_SET_DETAIL_DATA = "OBJECT_SET_DETAIL_DATA";
export const OBJECT_SET_MODIFY_DATA = "OBJECT_SET_MODIFY_DATA";

// nav
export const NAV_inUnityPage = "NAV_inUnityPage";
export const NAV_leaveUnityPage = "NAV_leaveUnityPage";
